import React from 'react';
import { SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, View } from 'react-native';
import { theme } from './src/theme';
import { features, privacyNotes, screens } from './src/data/features';

export default function App() {
  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="light-content" />
      <ScrollView contentContainerStyle={styles.content}>
        <View style={styles.heroCard}>
          <Text style={styles.eyebrow}>AUTOGENERATED MVP</Text>
          <Text style={styles.title}>Support Replay</Text>
          <Text style={styles.tagline}>Turn recurring support pain into a fixable product backlog.</Text>
        </View>

        <View style={styles.card}>
          <Text style={styles.sectionTitle}>Target user</Text>
          <Text style={styles.body}>Founders and small support/product teams handling user issues directly.</Text>
          <Text style={styles.sectionTitle}>Problem</Text>
          <Text style={styles.body}>Repeated support complaints live in inboxes and chats, making it hard to identify patterns and prioritize product fixes.</Text>
          <Text style={styles.sectionTitle}>Solution</Text>
          <Text style={styles.body}>A mobile-friendly issue pattern board that groups recurring user complaints into themes, evidence, and proposed fixes.</Text>
        </View>

        <View style={styles.card}>
          <Text style={styles.sectionTitle}>V1 features</Text>
          {features.map((feature) => (
            <View key={feature} style={styles.row}>
              <View style={styles.dot} />
              <Text style={[styles.body, styles.rowText]}>{feature}</Text>
            </View>
          ))}
        </View>

        <View style={styles.card}>
          <Text style={styles.sectionTitle}>Core screens</Text>
          {screens.map((screen) => (
            <View key={screen.title} style={styles.screenCard}>
              <Text style={styles.screenTitle}>{screen.title}</Text>
              <Text style={styles.body}>{screen.description}</Text>
            </View>
          ))}
        </View>

        <View style={styles.card}>
          <Text style={styles.sectionTitle}>Privacy notes</Text>
          {privacyNotes.map((note) => (
            <View key={note} style={styles.row}>
              <View style={[styles.dot, { backgroundColor: theme.colors.warning }]} />
              <Text style={[styles.body, styles.rowText]}>{note}</Text>
            </View>
          ))}
        </View>

        <View style={styles.card}>
          <Text style={styles.sectionTitle}>Monetization</Text>
          <Text style={styles.body}>Solo free tier, paid workspace features later.</Text>
          <Text style={styles.todo}>TODO: wire real data sources, storage, notifications, and analytics only after privacy review.</Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.background },
  content: { padding: 20, gap: 16 },
  heroCard: { backgroundColor: theme.colors.card, padding: 20, borderRadius: theme.radius, borderWidth: 1, borderColor: theme.colors.border },
  card: { backgroundColor: theme.colors.card, padding: 18, borderRadius: theme.radius, borderWidth: 1, borderColor: theme.colors.border, gap: 10 },
  eyebrow: { color: theme.colors.accent, fontSize: 12, fontWeight: '700', letterSpacing: 1.2 },
  title: { color: theme.colors.text, fontSize: 30, fontWeight: '800', marginTop: 8 },
  tagline: { color: theme.colors.muted, fontSize: 16, marginTop: 8, lineHeight: 24 },
  sectionTitle: { color: theme.colors.text, fontSize: 18, fontWeight: '700', marginTop: 4 },
  body: { color: theme.colors.muted, fontSize: 15, lineHeight: 22 },
  row: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  rowText: { flex: 1 },
  dot: { width: 10, height: 10, borderRadius: 999, backgroundColor: theme.colors.accent, marginTop: 6 },
  screenCard: { backgroundColor: '#0b1220', padding: 14, borderRadius: 12, borderWidth: 1, borderColor: theme.colors.border, gap: 6 },
  screenTitle: { color: theme.colors.text, fontSize: 16, fontWeight: '700' },
  todo: { color: theme.colors.warning, fontSize: 13, marginTop: 8, lineHeight: 20 },
});
