#!/usr/bin/env python3
import argparse
import json
import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def slugify(text: str) -> str:
    text = text.strip().lower()
    text = re.sub(r'[^a-z0-9]+', '-', text)
    return re.sub(r'-+', '-', text).strip('-')


def ensure_dir(path: Path):
    path.mkdir(parents=True, exist_ok=True)


def write(path: Path, content: str):
    ensure_dir(path.parent)
    path.write_text(content, encoding='utf-8')


def to_title(features):
    return '\n'.join([f"- {item}" for item in features])


def esc(s: str) -> str:
    return s.replace('`', '\\`')


def main():
    parser = argparse.ArgumentParser(description='Scaffold an Expo app from a JSON spec')
    parser.add_argument('--spec', required=True, help='Path to JSON spec')
    args = parser.parse_args()

    spec_path = Path(args.spec).resolve()
    spec = json.loads(spec_path.read_text(encoding='utf-8'))

    slug = spec.get('slug') or slugify(spec['app_name'])
    app_name = spec['app_name']
    package_name = spec['package_name']
    tagline = spec['tagline']
    theme_seed = spec.get('theme_seed', '#2563eb')
    target_user = spec.get('target_user', '')
    problem = spec.get('problem', '')
    solution = spec.get('solution', '')
    monetization = spec.get('monetization', '')
    privacy_notes = spec.get('privacy_notes', [])
    features = spec.get('feature_v1', [])
    screens = spec.get('screens', [
        {'title': 'Overview', 'description': 'Main dashboard section'},
        {'title': 'Features', 'description': 'Key product capabilities'},
    ])

    app_dir = ROOT / 'apps' / slug
    ensure_dir(app_dir / 'src' / 'data')

    package_json = {
        'name': slug,
        'version': '1.0.0',
        'private': True,
        'main': 'node_modules/expo/AppEntry.js',
        'scripts': {
            'start': 'expo start',
            'android': 'expo run:android',
            'web': 'expo start --web'
        },
        'dependencies': {
            'expo': '~53.0.0',
            'expo-status-bar': '~2.2.3',
            'react': '19.0.0',
            'react-native': '0.79.0'
        },
        'devDependencies': {
            '@types/react': '~19.0.10',
            'typescript': '~5.8.3'
        }
    }

    app_json = {
        'expo': {
            'name': app_name,
            'slug': slug,
            'version': '1.0.0',
            'orientation': 'portrait',
            'platforms': ['android'],
            'android': {
                'package': package_name,
                'adaptiveIcon': {
                    'backgroundColor': theme_seed
                }
            },
            'extra': {
                'tagline': tagline
            }
        }
    }

    eas_json = {
        'cli': {
            'version': '>= 10.0.0',
            'appVersionSource': 'remote'
        },
        'build': {
            'development': {'developmentClient': True, 'distribution': 'internal'},
            'preview': {'distribution': 'internal'},
            'production': {}
        },
        'submit': {
            'production': {}
        }
    }

    theme_ts = f"""export const theme = {{
  colors: {{
    background: '#0f172a',
    card: '#111827',
    text: '#f8fafc',
    muted: '#94a3b8',
    accent: '{theme_seed}',
    success: '#22c55e',
    warning: '#f59e0b',
    danger: '#ef4444',
    border: '#1f2937',
  }},
  radius: 16,
}};
"""

    features_ts = "export const features = " + json.dumps(features, indent=2) + ";\n\n" + \
        "export const screens = " + json.dumps(screens, indent=2) + ";\n\n" + \
        "export const privacyNotes = " + json.dumps(privacy_notes, indent=2) + ";\n"

    app_tsx = f"""import React from 'react';
import {{ SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, View }} from 'react-native';
import {{ theme }} from './src/theme';
import {{ features, privacyNotes, screens }} from './src/data/features';

export default function App() {{
  return (
    <SafeAreaView style={{styles.container}}>
      <StatusBar barStyle="light-content" />
      <ScrollView contentContainerStyle={{styles.content}}>
        <View style={{styles.heroCard}}>
          <Text style={{styles.eyebrow}}>AUTOGENERATED MVP</Text>
          <Text style={{styles.title}}>{esc(app_name)}</Text>
          <Text style={{styles.tagline}}>{esc(tagline)}</Text>
        </View>

        <View style={{styles.card}}>
          <Text style={{styles.sectionTitle}}>Target user</Text>
          <Text style={{styles.body}}>{esc(target_user)}</Text>
          <Text style={{styles.sectionTitle}}>Problem</Text>
          <Text style={{styles.body}}>{esc(problem)}</Text>
          <Text style={{styles.sectionTitle}}>Solution</Text>
          <Text style={{styles.body}}>{esc(solution)}</Text>
        </View>

        <View style={{styles.card}}>
          <Text style={{styles.sectionTitle}}>V1 features</Text>
          {{features.map((feature) => (
            <View key={{feature}} style={{styles.row}}>
              <View style={{styles.dot}} />
              <Text style={{[styles.body, styles.rowText]}}>{{feature}}</Text>
            </View>
          ))}}
        </View>

        <View style={{styles.card}}>
          <Text style={{styles.sectionTitle}}>Core screens</Text>
          {{screens.map((screen) => (
            <View key={{screen.title}} style={{styles.screenCard}}>
              <Text style={{styles.screenTitle}}>{{screen.title}}</Text>
              <Text style={{styles.body}}>{{screen.description}}</Text>
            </View>
          ))}}
        </View>

        <View style={{styles.card}}>
          <Text style={{styles.sectionTitle}}>Privacy notes</Text>
          {{privacyNotes.map((note) => (
            <View key={{note}} style={{styles.row}}>
              <View style={{[styles.dot, {{ backgroundColor: theme.colors.warning }}]}} />
              <Text style={{[styles.body, styles.rowText]}}>{{note}}</Text>
            </View>
          ))}}
        </View>

        <View style={{styles.card}}>
          <Text style={{styles.sectionTitle}}>Monetization</Text>
          <Text style={{styles.body}}>{esc(monetization)}</Text>
          <Text style={{styles.todo}}>TODO: wire real data sources, storage, notifications, and analytics only after privacy review.</Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}}

const styles = StyleSheet.create({{
  container: {{ flex: 1, backgroundColor: theme.colors.background }},
  content: {{ padding: 20, gap: 16 }},
  heroCard: {{ backgroundColor: theme.colors.card, padding: 20, borderRadius: theme.radius, borderWidth: 1, borderColor: theme.colors.border }},
  card: {{ backgroundColor: theme.colors.card, padding: 18, borderRadius: theme.radius, borderWidth: 1, borderColor: theme.colors.border, gap: 10 }},
  eyebrow: {{ color: theme.colors.accent, fontSize: 12, fontWeight: '700', letterSpacing: 1.2 }},
  title: {{ color: theme.colors.text, fontSize: 30, fontWeight: '800', marginTop: 8 }},
  tagline: {{ color: theme.colors.muted, fontSize: 16, marginTop: 8, lineHeight: 24 }},
  sectionTitle: {{ color: theme.colors.text, fontSize: 18, fontWeight: '700', marginTop: 4 }},
  body: {{ color: theme.colors.muted, fontSize: 15, lineHeight: 22 }},
  row: {{ flexDirection: 'row', alignItems: 'flex-start', gap: 10 }},
  rowText: {{ flex: 1 }},
  dot: {{ width: 10, height: 10, borderRadius: 999, backgroundColor: theme.colors.accent, marginTop: 6 }},
  screenCard: {{ backgroundColor: '#0b1220', padding: 14, borderRadius: 12, borderWidth: 1, borderColor: theme.colors.border, gap: 6 }},
  screenTitle: {{ color: theme.colors.text, fontSize: 16, fontWeight: '700' }},
  todo: {{ color: theme.colors.warning, fontSize: 13, marginTop: 8, lineHeight: 20 }},
}});
"""

    readme = f"""# {app_name}

{tagline}

Generated by Android Autopilot.

## Target user
{target_user}

## Problem
{problem}

## Solution
{solution}

## V1 features
{to_title(features)}

## Monetization
{monetization}

## Package name
`{package_name}`

## Run later
```bash
npm install
npm run start
```

## Notes
- This is a scaffolded Expo MVP.
- Replace sample content with real data and flows.
- Keep privacy disclosures aligned with implemented telemetry, notifications, and storage.
"""

    tsconfig = '{\n  "extends": "expo/tsconfig.base",\n  "compilerOptions": {\n    "strict": true\n  }\n}\n'

    write(app_dir / 'package.json', json.dumps(package_json, indent=2) + '\n')
    write(app_dir / 'app.json', json.dumps(app_json, indent=2) + '\n')
    write(app_dir / 'eas.json', json.dumps(eas_json, indent=2) + '\n')
    write(app_dir / 'tsconfig.json', tsconfig)
    write(app_dir / 'App.tsx', app_tsx)
    write(app_dir / 'src' / 'theme.ts', theme_ts)
    write(app_dir / 'src' / 'data' / 'features.ts', features_ts)
    write(app_dir / 'README.md', readme)

    print(f'Created Expo app scaffold at {app_dir}')


if __name__ == '__main__':
    main()
